### ISSUE TITLE
retrieve_user not async?

### ISSUE THREAD

**Issue by Garito** [ahopkins/sanic-jwt#16]
Hi!
Is this error:
```python
2017-11-03 02:13:53 - (sanic)[ERROR]: Exception occurred while handling uri: "http://localhost:8000/auth/me"
Traceback (most recent call last):
  File "/Users/garito/Lab/sanic/testRestAPI2/env/lib/python3.6/site-packages/sanic/app.py", line 503, in handle_request
    response = await response
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/Users/garito/Lab/sanic/testRestAPI2/env/lib/python3.6/site-packages/sanic_jwt/blueprint.py", line 80, in retrieve_user
    me = user.to_dict() if hasattr(user, 'to_dict') else dict(user)
AssertionError: yield from wasn't used with future
```
because retrieve_user can't be a coroutine? (async def retrieve_user)

Thanks!

**Comment by Garito** [comment]
Seems that extend_jwt_payload can't be async too
My issue here is that I would like to use motor to retrieve the user so retrieve_user and extend_jwt_payload must be coroutines

am I understanding it correctly?

Thanks!

**Comment by ahopkins** [comment]
Yup. Looks like that is definitely what is causing that problem. There is no reason that `extend_payload` should not be a coroutine.

I will make a quick patch.

**Comment by Garito** [comment]
Thanks a lot!

**Comment by ahopkins** [comment]
Take a look at https://github.com/ahopkins/sanic-jwt/releases/tag/v0.31

I just pushed a new bit of code to GitHub and pypi.

You should be able to:

    pip install sanic-jwt --upgrade

As a word of caution, I tested it by running the examples in the `./examples` folder. And, there is a partially complete `pytest` suite. It seems to be operable against both those checks. But I have not done a 100% thorough testing of the changes that I made.

Please let me know either way if something is not right, or if you are able to get motor working inside.

**Comment by Garito** [comment]
Giving the speed of your update, I'm ok with not being 100% tested
I've myself doing test so will catch (hopefully) any issues you missed and inform you asap

Thanks a lot
PS: Allow me to close this issues when I've tested it, yes?

**Comment by ahopkins** [comment]
Yes.

**Comment by Garito** [comment]
Hi again!
I've updated the library but I notice the lack of the async call for retrieve_user
I've checked the push (https://github.com/ahopkins/sanic-jwt/commit/4dd52b8a75ac1a12a40ee2ad19807f5023ecc972) but I can't see it there too
The code obviously fails

Could you add it, please? Or explain my misunderstanding?

Sorry for being a pain in the ass... :)
Thanks

**Comment by Garito** [comment]
By the way:
Correct me if I'm wrong (this will allow me to learn about your library)
You must add await to line 73 of blueprint.py (user = **await** request.app.auth.retrieve_user(request, payload))
am I correct?

**Comment by ahopkins** [comment]
@Garito Pain in the ass, you are not.

You are right that these following three methods should also be upgraded to coroutines:

- store_refresh_token
- retrieve_user
- retrieve_refresh_token

And, assuming they do become coroutines, then you are right that the the line in `blueprint.py` would need to await the return of that method.

In that absence, to use a library like `motor` makes sense that it would fail in this context.

Could you perhaps post a snippet of code showing how you would like to be using it? Then I can both help you, and make some improvements to the library.

It will probably take me a little bit more time to work this one out. Not because it is complex, but because I want to run through the code and make sure that every coroutine is setup right.

It also might be helpful to put together an example integration with some popular tools like `motor`. And, if you would be up for it, it would be awesome if you could put together a sort of barebones example script.

**Comment by Garito** [comment]
Giving the help code:
```python
def retrieve_user(request, payload, *args, **kwargs):
    if payload:
        user_id = payload.get('user_id', None)
        user = User.get(user_id=user_id)
        return user
    else:
        return None
```
with motor & async would be something like
```python
async def retrieve_user(request, payload, *args, **kwargs):
    if payload:
        user_id = payload.get(request.app.config["SANIC_JWT_USER_ID"], None)
        if user_id:
            user = await request.app.mongo.db.users.find({"_id": user_id})
            return user

    return None
```
assuming the programmer has putted the motor client @ request.app.mongo and that the database has been called db

I want to point that you must use SANIC_JWT_USER_ID as user_id getter cause I've noticed the library don't respect that key everywere (I would report if I found those again)

Are you meaning and example like this?

**Comment by ahopkins** [comment]
Thanks @Garito 

This is very helpful.

**Comment by Garito** [comment]
Hi!
I've edit the line and added the await with success
If I encounter any issue I will comment here while giving you time to make the modification and the tests

**Comment by ahopkins** [comment]
@Garito Thanks! Just pushed a commit to fix some of them. I will comb through my code a little more closely, run some more tests, and push out a patch either later tonight tor tomorrow. Not sure if it was a bug as much as my forgetting to circle back to this item ;-)

**Comment by Garito** [comment]
Yeah, sounds that last one
Will close this if that last update solves this or comment if not

Thanks!

**Comment by vltr** [comment]
@ahopkins, [from your request](https://github.com/ahopkins/sanic-jwt/issues/16#issuecomment-341993546):
> Could you perhaps post a snippet of code showing how you would like to be using it? Then I can both help you, and make some improvements to the library.

Here are two simple examples, using [aioredis](https://github.com/aio-libs/aioredis) in a more "explicit way" (so to speak) than the redis usage in your examples (as quoted in #39):

```python
async def store_refresh_token(user_id, refresh_token, *args, **kwargs):
    key = 'refresh_token_{user_id}'.format(user_id=user_id)
    async with app.redis_pool.get() as redis:
        await redis.set(key, refresh_token)


async def retrieve_refresh_token(user_id, *args, **kwargs):
    key = 'refresh_token_{user_id}'.format(user_id=user_id)
    async with app.redis_pool.get() as redis:
        return await redis.get(key)
```

So, we can get rid of the following message:

```
/opt/pyenv/versions/wrk-3.6.4/lib/python3.6/site-packages/sanic_jwt/authentication.py:141: RuntimeWarning: coroutine 'store_refresh_token' was never awaited
  self.store_refresh_token(user_id=user_id, refresh_token=refresh_token)
```

If there's anything I could help, please let me know :wink:

**Comment by ahopkins** [comment]
@vltr 

Thanks. I just pushed a small commit to add `async/await` for `store_refresh_token` and `retrieve_refresh_token`. You can pull it from GitHub. I have not pushed it to pypi yet as I want to make some more tweaks before I do.

As for making a PR, please feel free.

I think the next big thing I want to work on is some better logging integration, and allowing more customized responses. And, of course, a whole new set of docs.

**Comment by vltr** [comment]
Thanks, @ahopkins ! I'm already working on a copy of your repo, but I think I'll fork so I can work with PRs. IMO, don't worry about pypi - this needs some work to be done yet.

About logging, what do you have in mind? Since there's a blueprint (and its routes) that integrates with Sanic, it already uses Sanic's own log. I also saw some `print`s - I believe for debugging purposes. Also, is flake8 / pep8 compliance and coverage something you want to add to the project?

Cheers!

**Comment by ahopkins** [comment]
@vltr Thanks. Agreed. Lots of work still to do on this one. I have a separate local version that I am pulling into a project of mine that I will be putting into production soon with a lot of changes that I want to integrate.

Yes, the code is littered with comments and `print` that need to be cleaned up and removed. My thought for logging was to extend off the `sanic` logging module and specifically allow for logging of failed attempts.

There are a slew of more tests to write, and yes pep8 is on the radar. It should be there most of the way because my editor yells at me loudly if I have pep8 violations. But there is not `tox` or anything like that running yet.

**Comment by Garito** [comment]
About the logger:
For me the best way to solve this is to add a specific logger to sanic-jwt in order to turn on and off when needed

**Comment by vltr** [comment]
@ahopkins at least, for developing purposes, we can let pep8 in quite loose (I'll be adding it, it's pretty quick) and codecov for tests, it gives very good insights on testing. About `tox`, I'll wouldn't bother about it now (as with pypi).

About logging, I agree with @Garito about a specific `sanic-jwt` logger, but I'm kinda resilient based on the belief of user defined logging and the usage of exceptions that the developer can handle and log itself - something like [requests](https://github.com/requests/requests) do - and described by the author [here](http://docs.python-guide.org/en/latest/writing/logging/). Let me know your thoughts :wink:

**Comment by Garito** [comment]
Seems ok to me the logging thing

**Comment by ahopkins** [comment]
I agree that there needs to be developer control. That is in essence what I tried to achieve with the package. Developer decides how to authenticate, define users, override payload handlers, scoping, etc. But, in the absence of developer input, there should be an easy way to handle logging of all requests, failed requests, or perhaps a certain subset of exceptions. Complete developer control, with a sensible set of defaults for easy implementation. Tied into this is should be defining how exceptions are handled in dev and production environments.

Hopefully I will get my current time drain project released soon and I can turn back to this and push it forward and clear up some of these open issues.

**Comment by vltr** [comment]
[I *started* with](https://github.com/vltr/sanic-jwt/blob/master/sanic_jwt/__init__.py#L1) `import logging` into the `__init__.py` file, for now ...
